lista_barrios = ["Popular 1",
"Popular 2",
"Santo Domingo Savio 1",
"Santo Domingo Savio 2",
"Granizal",
"Moscú 2",
"Villa Guadalupe",
"San Pablo",
"Aldea Pablo VI",
"La Esperanza 2",
"El Compromiso",
"La Avanzada",
"Carpinelo",
"El Rodeo",
"Santa Cruz",
"La Isla",
"El Playón de Los Comuneros",
"Pablo VI",
"La Frontera",
"La Francia",
"Andalucía",
"Villa del Socorro",
"Villa Niza",
"Moscú 1",
"La Rosa",
"La Salle",
"Las Granjas",
"Campo Valdes 2",
"Santa Inés",
"El Raizal",
"El Pomar",
"Manrique Central 2",
"Manrique Oriental",
"Versalles 1",
"Versalles 2",
"La Cruz",
"La Honda",
"Oriente",
"Maria Cano – Carambolas",
"San José La Cima 1",
"San José La Cima",
"Aranjuez",
"Berlín",
"San Isidro",
"Palermo",
"Bermejal – Los Álamos",
"Moravia",
"Sevilla",
"San Pedro",
"Manrique Central 1",
"Campo Valdes 1",
"Las Esmeraldas",
"La Piñuela",
"Brasilia",
"Miranda",
"Castilla",
"Toscana",
"Héctor Abad Gómez",
"La Paralela",
"Las Brisas",
"Florencia",
"Tejelo",
"Boyacá",
"Belalcazar",
"Girardot",
"Tricentenario",
"Francisco Antonio Zea",
"Alfonso López",
"Caribe",
"El Progreso",
"Doce de Octubre 1",
"Doce de Octubre 2",
"Santander",
"Pedregal",
"La Esperanza",
"San Martín de Porres",
"Kennedy",
"Picacho",
"Picachito",
"Mirador del Doce",
"El Progreso 2",
"El Triunfo",
"Robledo",
"El Volador",
"San Germán",
"Barrio Facultad de Minas",
"La Pilarica",
"Bosques de San Pablo",
"Altamira",
"Córdoba",
"López de Mesa",
"El Diamante",
"Aures 1",
"Aures 2",
"Bello Horizonte",
"Villa Flora",
"Palenque",
"Cucaracho",
"Fuente Clara",
"Santa Margarita",
"Olaya Herrera",
"Pajarito",
"Monteclaro",
"Villa de La Iguaná",
"La Cuchilla",
"La Aurora",
"Villa Hermosa",
"La Mansión",
"San Miguel",
"La Ladera",
"Golondrinas",
"Batallón Girardot",
"Llanaditas",
"Los Mangos",
"Enciso",
"Sucre",
"El Pinal",
"Trece de Noviembre",
"La Libertad",
"Villatina",
"San Antonio",
"Las Estancias",
"Villa Turbay",
"La Sierra",
"Villa Lilliam",
"Esfuerzos de Paz 1",
"Esfuerzos de Paz 2",
"Buenos Aires",
"Caicedo",
"Juan Pablo II",
"Ocho de Marzo",
"Barrios de Jesús",
"Bomboná 2",
"Los Cerros – El Vergel",
"Alejandro Echavarría",
"Miraflores",
"Cataluña",
"La Milagrosa",
"Gerona",
"El Salvador",
"Loreto",
"Asomadera 1",
"Asomadera 2",
"Asomadera 3",
"Quinta Linda",
"Barrio Pablo Escobar",
"La Candelaria",
"Prado",
"Jesús Nazareno",
"El Chagualo",
"Estación Villa",
"San Benito",
"Guayaquil",
"Corazón de Jesús – Barrio Triste",
"Calle Nueva",
"Perpetuo Socorro",
"Barrio Colón",
"Las Palmas",
"Bomboná 1",
"Boston",
"Los Ángeles",
"Villa Nueva",
"San Diego",
"Los Conquistadores",
"Laureles",
"Carlos E. Restrepo",
"Suramericana",
"Naranjal",
"San Joaquín",
"Bolivariana",
"Las Acacias",
"La Castellana",
"Lorena",
"El Velódromo",
"Estadio",
"Los Colores",
"Cuarta Brigada",
"Florida Nueva",
"La América",
"Ferrini",
"Calasanz",
"Los Pinos",
"La Floresta",
"Santa Lucía",
"El Danubio",
"Campo Alegre",
"Santa Mónica",
"Barrio Cristóbal",
"Simón Bolívar",
"Santa Teresita",
"Calasanz Parte Alta",
"San Javier 1",
"San Javier 2",
"El Pesebre",
"Blanquizal",
"Santa Rosa de Lima",
"Los Alcázares",
"Metropolitano",
"La Pradera",
"Juan XXIII",
"La Divisa",
"Veinte de Julio",
"Belencito",
"Betania",
"El Corazón",
"Las Independencias",
"Nuevos Conquistadores",
"El Salado",
"Eduardo Santos",
"Peñitas",
"Antonio Nariño",
"El Socorro",
"Calasania",
"Castropol",
"Barrio Colombia",
"Villa Carlota",
"Lalinde",
"Manila",
"Las Lomas 1",
"Las Lomas 2",
"Altos del Poblado",
"El Tesoro",
"Los Naranjos",
"Los Balsos 1",
"Los Balsos 2",
"San Lucas",
"El Diamante",
"El Castillo",
"Alejandría",
"La Florida",
"El Poblado",
"Astorga",
"Patio Bonito",
"La Aguacatala",
"Santa María de Los Ángeles",
"Tenche",
"Trinidad",
"Santa Fe",
"Campo Amor",
"Cristo Rey",
"Guayabal",
"La Colina",
"Belén",
"Cerro Nutibara",
"Fátima",
"Rosales",
"Granada",
"San Bernardo",
"Las Playas",
"Diego Echavarria",
"La Mota",
"El Rincón",
"La Hondonada",
"La Loma de Los Bernal",
"La Gloria",
"Altavista",
"La Palma",
"Zafra",
"Los Alpes",
"Las Violetas",
"Las Mercedes",
"Nueva Villa de Aburrá",
"Miravalle",
"El Nogal – Los Almendros"]

lista_sexos = ["Hombre", "Mujer", "Otro"]