# Generated by Django 4.1 on 2022-09-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descuento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='nuevo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='precioAnterior',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidades',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
