# Generated by Django 4.1 on 2022-10-17 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_factura_detallefactura'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='subTotal',
            field=models.IntegerField(default=0),
        ),
    ]
