# Generated by Django 4.1 on 2022-11-06 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_rename_rating_calificar_p0_remove_calificar_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='calificar',
            new_name='Review',
        ),
    ]
