# Generated by Django 4.1 on 2022-11-07 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_favorito_detallefavorito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefavorito',
            name='idFavorito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.favorito'),
        ),
    ]
