# Generated by Django 4.1 on 2022-10-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='popularidad',
            field=models.IntegerField(default=0),
        ),
    ]
