# Generated by Django 4.0.6 on 2022-10-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_remove_usuario_id_remove_usuario_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='primer_nombre',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='primer_apellido',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='idUsuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='correo',
        ),
    ]
