# Generated by Django 4.0.6 on 2022-10-09 02:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='edad',
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='barrio',
            field=models.CharField(default='elBarrio', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(default='laDireccion', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(default='indeterminado', max_length=16),
            preserve_default=False,
        ),
    ]
