# Generated by Django 4.0.6 on 2022-10-15 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0013_remove_usuario_edad_usuario_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('idFactura', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.IntegerField(default=0)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoComprado',
            fields=[
                ('idProductoComprado', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('idFactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.factura')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
            ],
        ),
    ]
